spring.application.name=Expense_Manager

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://ep-empty-bird-aopfc4gz-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_xNvro8A9TnXy
spring.datasource.driver-class-name=org.postgresql.Driver
 
# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect